// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
// 1, 2, 3, 5, 8, 13, 21, ...

public class problem2 {

    public static int fibonacci() {

        int current = 1; 
        int next = 2; 
        int sum = 0;

        // sum of even valued values
        while (current <= 4000000) {

            if (current % 2 == 0) {
                sum += current;
            }

            int temp = current + next;
            current = next;
            next = temp;
        }

        return sum;
    }

    public static void main(String[] args) {
        int finalSum = fibonacci();
        System.out.println(finalSum);
    }
}
